# Generated by Django 5.2.3 on 2025-06-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='Workshop', max_length=100),
            preserve_default=False,
        ),
    ]
